version: '3.2'

services:
   db:
      image: mysql:latest
      container_name: escBD
      restart: always
      ports:
       - '3306:3306'
      environment:
        MYSQL_ROOT_PASSWORD: helloworld
  
   app:
      depends_on:
       - db
      image: phpmyadmin/phpmyadmin
      container_name: escPhpmyadmin
      restart: always
      ports:
       - '8080:80'
      environment:
        PMA_HOST: db
